### ISSUE TITLE
UVLoader fails if module info is not located in the first segment

### ISSUE THREAD

**Issue by xyzz** [yifanlu/UVLoader#7]
`uvl_elf_get_module_info` is used to retrieve segment index here: https://github.com/yifanlu/UVLoader/blob/74ef728efe875d2087a27e54de6e143a33a2d86e/load.c#L277 however it can only return -1 or 0.

**Comment by yifanlu** [comment]
Fixed with 1d83d7b2bda7d2161c20e1db49d4681d59e04c60
